### ISSUE TITLE
ovirt-csi-driver container reports OS mismatch when pulled on okd 4.4.0

### ISSUE THREAD

**Issue by abaxo** [oVirt/csi-driver#15]
Hi all, 

Sorry if this isn't the right place for this bug ticket. I am using @rgolangh 's quay.io ovirt-csi-driver image which was updated today. Part of the update seems to have broken the ovirt-csi-driver container from running in the pod with the error:
`Failed to pull image "quay.io/rgolangh/ovirt-csi-driver:latest": rpc error: code = Unknown desc = Image operating system mismatch: image uses "", expecting "linux"`

Many thanks
Craig

**Comment by rgolangh** [comment]
@bennyz did you chage something in the Dockerfile?

**Comment by rgolangh** [comment]
@bennyz it may be related to how you build the image.

**Comment by bennyz** [comment]
looks related to https://github.com/containers/buildah/issues/2225

**Comment by abaxo** [comment]
I'm not sure if you've done an update since, but I've just done a fresh install on a fresh OKD4.4 cluster and it has worked this time.

**Comment by rgolangh** [comment]
with the same csi driver image?

**Comment by abaxo** [comment]
Good question. I don't have the logs anymore from the previous instance where it was failing. It is now running from:
```
imageID: >-
        quay.io/rgolangh/ovirt-csi-driver@sha256:4ef883a62b64457952dc7c938b91a126ce9f5da1550469253eecdeee99a2222c
      image: 'quay.io/rgolangh/ovirt-csi-driver:latest'
```

I have bounced the pod a few times, and I can't reproduce the issue.

**Comment by abaxo** [comment]
I havent been able to reproduce this in a few builds, so gonna chalk it up as something htat has already been fixed.
