### ISSUE TITLE
Disks appear to be formatted each time they are mounted

### ISSUE THREAD

**Issue by abaxo** [oVirt/csi-driver#23]
Hey everyone,

So I've had a couple of times when I have restarted pods and then though had been going crazy when the pod comes back up but the volume is empty. I had previously chalked it up to buggy containers, or human error. I've just been having a play with deploying something and have caught the csi-node pod formatting (at least attempting to) the PVC multiple times, and the mkfs failing. The net result for this specific PV is that the data is wiped. 

Logs: [ovirt-csi-node-qh4gg-ovirt-csi-driver.log](https://github.com/oVirt/csi-driver/files/4604613/ovirt-csi-node-qh4gg-ovirt-csi-driver.log)

**In order to repeat the behaviour:**
0) have an okd 4.4-beta4 cluster running on oVirt 4.3.9 (I dont think the oVirt version matters here)
1) deploy the ovirt-csi-driver
2) create a pvc and attach it to a container through deployment config (don't know if this matters for this behaviour, but it is what I am doing)
3) put some dummy data in the pvc from within the pod
4) restart your pod
5) data is gone and csi-node log shows mkfs was attempted and failed.

I hope that I am just being an idiot and doing something wrong, but I can't for the life of me spot it. I have nothing different on the cluster away from defaults for the SC or PVC and have seen this behavior on multiple clusters.

Cheers
Craig

**Comment by abaxo** [comment]
I suspect what is happening is that getDeviceInfo (https://github.com/oVirt/csi-driver/blob/master/pkg/service/node.go#L44) is returning the filesystem var as "" (empty), because the next conditional block which depends on that condition always fires.

When that fires, the makeFS function is being called, which has an option that if the filesystem is ext* then it will *always* force makefs on the device. (https://github.com/oVirt/csi-driver/blob/93ddbfad819c64c66c5af2c2a10eb82caa70031d/pkg/service/node.go#L179-L183)

Lets see if I can figure out how to develop go...

**Comment by bennyz** [comment]
Thanks for the report! Your analysis is right, `lsblk` seems to always have the FSTYPE field empty. I have patch using `blkid` instead that works, I'll send it tomorrow

**Comment by abaxo** [comment]
Nice, thanks @bennyz ! I had wondered about blkid usage too after reading through https://github.com/chef/ohai/issues/351 which poses some good arguments not to use it. I have just applied the patch to my daemonset and the behaviour is as expected, works a treat.

**Comment by rgolangh** [comment]
Benny and I saw that lsblk needs udev passed to the container which does the staging. 
Handled by #26 and #27
