### ISSUE TITLE
readme deploy instructions: namespaces "ovirt-csi-driver" not found

### ISSUE THREAD

**Issue by jasonbrooks** [oVirt/csi-driver#30]
On a newly installed OKD 4.4 cluster on RHV 4.3.9, `oc create -f deploy/csi-driver` yields:

```
csidriver.storage.k8s.io/csi.ovirt.org created
namespace/openshift-ovirt-csi-operator created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-controller-provisioner-binding created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-controller-attacher-binding created
clusterrole.rbac.authorization.k8s.io/ovirt-csi-controller-cr created
clusterrole.rbac.authorization.k8s.io/ovirt-csi-node-cr created
clusterrole.rbac.authorization.k8s.io/openshift:csi-driver-controller-leader-election created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-controller-binding created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-leader-binding created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-node-binding created
clusterrolebinding.rbac.authorization.k8s.io/ovirt-csi-node-leader-binding created
credentialsrequest.cloudcredential.openshift.io/ovirt-csi-driver created
Error from server (NotFound): error when creating "deploy/csi-driver/020-autorization.yaml": namespaces "ovirt-csi-driver" not found
Error from server (NotFound): error when creating "deploy/csi-driver/020-autorization.yaml": namespaces "ovirt-csi-driver" not found
Error from server (NotFound): error when creating "deploy/csi-driver/030-node.yaml": namespaces "ovirt-csi-driver" not found
Error from server (NotFound): error when creating "deploy/csi-driver/040-controller.yaml": namespaces "ovirt-csi-driver" not found
Error from server (AlreadyExists): error when creating "deploy/csi-driver/060-credential-request.yaml": credentialsrequests.cloudcredential.openshift.io "ovirt-csi-driver" already exists
```

Should the manifests be adapted to create the `ovirt-csi-driver` namespace? Or should instances of that namespace be changed to `openshift-ovirt-csi-operator`? Also, I don't see an operator installed / created as a result of this command. Is that the expected behavior?

**Comment by jasonbrooks** [comment]
Related, `deploy/csi-driver/040-controller.yaml` includes a statefulset, `ovirt-csi-plugin`, that includes a container, `prepare-ovirt-config`, that writes an `ovirt-config.yaml` file.

This file looks to the `ovirt-credentials` secret for its values, and includes `ovirt_cafile` but not `ovirt_ca_bundle` -- according to guideance elsewhere, I've included the ca bundle in my `ovirt-config.yaml` not not the ca file value, so I'm getting untrusted cert errors.

**Comment by bennyz** [comment]
You are right, namespace is missing from the manifests, ideally the operator would have taken care of this, but we have to switch to a regular operator instead of CVO because we have no conditional enabling there. I will add the namespace manifest to `deploy/`.

I will check the ca issue issue on Sunday

**Comment by rgolangh** [comment]
handled by #32
