### ISSUE TITLE
OKD 4.4 on oVirt 4.3 - oVirt CSI driver - PVC bound Successfully - MountVolume.MountDevice failed for volume "pvc-620d2db6-d845-4b4c-9220-d7e372d30397" : rpc error: code = Unknown desc = exit status 32lsblk failed with lsblk: .: not a block device

### ISSUE THREAD

**Issue by kcns008** [oVirt/csi-driver#31]
When trying to deploy Wordpress from

https://raw.githubusercontent.com/openshift-evangelists/wordpress-quickstart/master/templates/classic-standalone.json

on OKD 4.4 on oVirt 4.3 - oVirt CSI driver

getting the following error after PVC bound Successfully

MountVolume.MountDevice failed for volume "pvc-620d2db6-d845-4b4c-9220-d7e372d30397" : rpc error: code = Unknown desc = exit status 32lsblk failed with lsblk: .: not a block device

**Comment by bennyz** [comment]
Do you have the changes from this PR #26?
The important ones are from this commit: https://github.com/oVirt/csi-driver/pull/26/commits/4e2d32d88d5719c4cfdec887ecdaed280fa238fc

**Comment by kcns008** [comment]
@bennyz Thanks for your reply. 
yes, looks like I have changes from PR #26 

here my DaemonSet - oVirt-csi-node - yaml

kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ovirt-csi-node
  namespace: ovirt-csi-driver
  resourceVersion: '10487651'
  generation: 1
  creationTimestamp: '2020-05-16T03:59:53Z'
  annotations:
    deprecated.daemonset.template.generation: '1'
spec:
  selector:
    matchLabels:
      app: ovirt-csi-driver
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ovirt-csi-driver
    spec:
      restartPolicy: Always
      initContainers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: prepare-ovirt-config
          command:
            - /bin/sh
            - '-c'
            - |
              #!/bin/sh
              cat << EOF > /tmp/config/ovirt-config.yaml
              ovirt_url: $OVIRT_URL
              ovirt_username: $OVIRT_USERNAME
              ovirt_password: $OVIRT_PASSWORD
              ovirt_cafile: $OVIRT_CAFILE
              ovirt_insecure: $OVIRT_INSECURE
              EOF
          env:
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: /tmp/config
          terminationMessagePolicy: File
          image: busybox
      serviceAccountName: ovirt-csi-node-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: csi-driver-registrar
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          terminationMessagePolicy: File
          image: 'quay.io/k8scsi/csi-node-driver-registrar:v1.2.0'
          args:
            - '--v=5'
            - '--csi-address=/csi/csi.sock'
            - >-
              --kubelet-registration-path=/var/lib/kubelet/plugins/ovirt.org/csi.sock
        - resources: {}
          terminationMessagePath: /dev/termination-log
          name: ovirt-csi-driver
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: OVIRT_CONFIG
              value: /tmp/config/ovirt-config.yaml
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
          imagePullPolicy: Always
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: config
              mountPath: /tmp/config/
            - name: plugin-dir
              mountPath: /var/lib/kubelet/plugins
              mountPropagation: Bidirectional
            - name: host-dev
              mountPath: /dev
            - name: udev
              mountPath: /run/udev
            - name: mountpoint-dir
              mountPath: /var/lib/kubelet/pods
              mountPropagation: Bidirectional
          terminationMessagePolicy: File
          image: 'quay.io/rgolangh/ovirt-csi-driver:latest'
          args:
            - '--endpoint=unix:/csi/csi.sock'
            - '--namespace=ovirt-csi-driver'
            - '--node-name=$(KUBE_NODE_NAME)'
      serviceAccount: ovirt-csi-node-sa
      volumes:
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry/
            type: Directory
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins
            type: Directory
        - name: socket-dir
          hostPath:
            path: /var/lib/kubelet/plugins/ovirt.org/
            type: DirectoryOrCreate
        - name: host-dev
          hostPath:
            path: /dev
            type: ''
        - name: udev
          hostPath:
            path: /run/udev
            type: ''
        - name: config
          emptyDir: {}
        - name: mountpoint-dir
          hostPath:
            path: /var/lib/kubelet/pods
            type: DirectoryOrCreate
      dnsPolicy: ClusterFirst
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  revisionHistoryLimit: 10
status:
  currentNumberScheduled: 4
  numberMisscheduled: 0
  desiredNumberScheduled: 4
  numberReady: 4
  observedGeneration: 1
  updatedNumberScheduled: 4
  numberAvailable: 4

**Comment by bennyz** [comment]
Thank you, any chance you can share the full logs?

**Comment by kcns008** [comment]
https://i.imgur.com/hVC8xdj.png



I0522 13:55:31.906308       1 csi_handler.go:116] Attaching "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.906316       1 csi_handler.go:249] Starting attach operation for "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.906379       1 csi_handler.go:209] PV finalizer is already set on "pvc-163a3ed8-f79b-450e-920c-6d8b3165d3d3"
I0522 13:55:31.906409       1 csi_handler.go:542] Found NodeID d0d2c675-abb7-43a1-96b8-6e7bc0ff1618 in CSINode okd4-h255v-worker-0-hjsnh
I0522 13:55:31.906427       1 csi_handler.go:169] VA finalizer is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.906435       1 csi_handler.go:183] NodeID annotation is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.946601       1 csi_handler.go:412] Saving attach error to "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.951526       1 csi_handler.go:423] Saved attach error to "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:31.951599       1 csi_handler.go:99] Error processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31": failed to attach: rpc error: code = Unknown desc = Fault reason is "Operation Failed". Fault detail is "[Cannot attach Virtual Disk: The following disks are locked: pvc-163a3ed8-f79b-450e-920c-6d8b3165d3d3. Please try again in a few minutes.]". HTTP response code is "409". HTTP response message is "409 Conflict".
I0522 13:55:32.906486       1 controller.go:175] Started VA processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.906544       1 csi_handler.go:89] CSIHandler: processing VA "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.906577       1 csi_handler.go:116] Attaching "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.906591       1 csi_handler.go:249] Starting attach operation for "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.906689       1 csi_handler.go:209] PV finalizer is already set on "pvc-163a3ed8-f79b-450e-920c-6d8b3165d3d3"
I0522 13:55:32.906734       1 csi_handler.go:542] Found NodeID d0d2c675-abb7-43a1-96b8-6e7bc0ff1618 in CSINode okd4-h255v-worker-0-hjsnh
I0522 13:55:32.906760       1 csi_handler.go:169] VA finalizer is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.906772       1 csi_handler.go:183] NodeID annotation is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.935872       1 csi_handler.go:412] Saving attach error to "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.942723       1 controller.go:141] Ignoring VolumeAttachment "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31" change
I0522 13:55:32.942947       1 csi_handler.go:423] Saved attach error to "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:32.942988       1 csi_handler.go:99] Error processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31": failed to attach: rpc error: code = Unknown desc = Fault reason is "Operation Failed". Fault detail is "[Cannot attach Virtual Disk: The following disks are locked: pvc-163a3ed8-f79b-450e-920c-6d8b3165d3d3. Please try again in a few minutes.]". HTTP response code is "409". HTTP response message is "409 Conflict".
I0522 13:55:36.943330       1 controller.go:175] Started VA processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:36.943378       1 csi_handler.go:89] CSIHandler: processing VA "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:36.943388       1 csi_handler.go:116] Attaching "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:36.943397       1 csi_handler.go:249] Starting attach operation for "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:36.943455       1 csi_handler.go:209] PV finalizer is already set on "pvc-163a3ed8-f79b-450e-920c-6d8b3165d3d3"
I0522 13:55:36.943475       1 csi_handler.go:542] Found NodeID d0d2c675-abb7-43a1-96b8-6e7bc0ff1618 in CSINode okd4-h255v-worker-0-hjsnh
I0522 13:55:36.943502       1 csi_handler.go:169] VA finalizer is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:36.943511       1 csi_handler.go:183] NodeID annotation is already set on "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.740259       1 csi_handler.go:129] Attached "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.740295       1 util.go:35] Marking as attached "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748379       1 util.go:48] Marked as attached "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748462       1 csi_handler.go:135] Fully attached "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748505       1 csi_handler.go:105] CSIHandler: finished processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748604       1 controller.go:175] Started VA processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748642       1 csi_handler.go:89] CSIHandler: processing VA "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"
I0522 13:55:37.748659       1 csi_handler.go:111] "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31" is already attached
I0522 13:55:37.748674       1 csi_handler.go:105] CSIHandler: finished processing "csi-0a689d4e7a9d4d0937bbf188c42bd4536552f1f1c1b9339b94b632cb3e8f6b31"

**Comment by bennyz** [comment]
Hi, apologies for the delay. We pushed a lot of fixes recently, I suspect your issue may be related to https://github.com/oVirt/csi-driver/pull/34, it would be great if you can try this and report back

**Comment by kcns008** [comment]
@bennyz Thanks for your reply... I will be deployed

**Comment by mriedmann** [comment]
Hi! We hit the exact same problem using an image built from master branch image with OpenShift 4.4.6 and oVirt 4.3 (IPI Installation). Any suggestions how we can debug that? Thx!

**Comment by bennyz** [comment]
@mriedmann thanks for the report, any chance you have earlier logs? namely:
```go
	klog.Infof("Extracting pvc volume name %s", volumeID)
```
Should be something like this:
```
I0601 16:04:36.691620       1 driver.go:39] Setting the rpc server
I0603 15:37:52.297449       1 node.go:41] Staging volume 014a1713-2c6a-4656-ab7e-81094b96e230 with volume_id:"014a1713-2c6a-4656-ab7e-81094b96e230" staging_target_path:"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-10042a9d-0e8b-4671-9ec0-da4ea8aa6d62/globalmount" volume_capability:<mount:<fs_type:"ext4" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:"storage.kubernetes.io/csiProvisionerIdentity" value:"1591174861876-8081-csi.ovirt.org" >
I0603 15:37:52.616901       1 node.go:151] Extracting pvc volume name 014a1713-2c6a-4656-ab7e-81094b96e230
I0603 15:37:52.696902       1 node.go:158] Extracted pvc volume name 014a1713-2c6a-4656-a
I0603 15:37:52.697803       1 node.go:178] lsblk -nro FSTYPE /dev/sdb
I0603 15:37:52.741993       1 node.go:63] Creating FS ext4 on device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_014a1713-2c6a-4656-a
I0603 15:37:52.742162       1 node.go:198] Mounting device /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_014a1713-2c6a-4656-a, with FS ext4
I0603 15:37:52.938611       1 node.go:151] Extracting pvc volume name 014a1713-2c6a-4656-ab7e-81094b96e230
I0603 15:37:52.985048       1 node.go:158] Extracted pvc volume name 014a1713-2c6a-4656-a
I0603 15:37:52.985210       1 node.go:92] Mounting devicePath /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_014a1713-2c6a-4656-a, on targetPath: /var/lib/kubelet/pods/500cc371-60e5-496a-a8aa-d489f1adffcf/volumes/kubernetes.io~csi/pvc-10042a9d-0e8b-4671-9ec0-da4ea8aa6d62/mount with FS type: ext4
```
Also, in the troubleshooting section in the README, there are instructions how to log into the pod, if you can please check `ls -l /dev/disk/by-id/<truncated disk id>` to see where it points, so we can better understand why `.` is returned from `filepath.EvalSymlinks`

Thanks, and sorry for the inconvenience

**Comment by mriedmann** [comment]
We found the problem. An error on https://github.com/oVirt/csi-driver/blob/master/pkg/service/node.go#L83 was silently dropped. It was a certificate trust issue but without the error message it was impossible to find. We added some error logging to find it. I will do a pull request in some minutes. 
Thank you nevertheless :)

**Comment by bennyz** [comment]
Excellent, thank you!

**Comment by sandrobonazzola** [comment]
This repository is inactive, please refer to: https://github.com/openshift/ovirt-csi-driver
