### ISSUE TITLE
Is this repository up2date?

### ISSUE THREAD

**Issue by kissi7** [oVirt/csi-driver#60]
Hello, is this repository up2date or is being replaced by https://github.com/openshift/ovirt-csi-driver?

**Comment by bennyz** [comment]
yes, development is being on the openshift repository, I'll add a notice in the README like we have in the csi-driver-operator repo https://github.com/ovirt/csi-driver-operator/

We did consider using this repo as an "upstream repo" but there doesn't seem to be a substantial benefit currently

**Comment by sandrobonazzola** [comment]
This repository is inactive, please refer to: https://github.com/openshift/ovirt-csi-driver
